import config from '@payload-config'
import { getPayload } from 'payload'
import { notFound } from 'next/navigation'
import { Badge } from '@/components/ui/badge'
import { FavoriteButton } from '@/components/agent/FavoriteButton'
import { DownloadButton } from '@/components/agent/DownloadButton'
import { VersionList } from '@/components/agent/VersionList'
import { ScreenshotGallery } from '@/components/agent/ScreenshotGallery'
export default async function AgentDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const payload=await getPayload({config});const found=await payload.find({collection:'agents',where:{and:[{slug:{equals:slug}},{status:{equals:'published'}}]},limit:1,depth:1});const agent=found.docs[0];if(!agent)return notFound();const versions=await payload.find({collection:'agent-versions',where:{and:[{agent:{equals:agent.id}},{status:{equals:'published'}}]},sort:'-publishedAt'});const latest=versions.docs[0];return <article><div className="rounded-[var(--radius)] bg-gradient-to-br from-blue-100 via-white to-sky-50 p-8 md:p-12"><Badge>鲸创官方</Badge><h1 className="mt-4 text-4xl font-bold tracking-tight">{agent.name}</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">{agent.summary}</p><div className="mt-7 flex flex-wrap gap-3"><FavoriteButton agentId={agent.id}/>{agent.demoUrl&&<a className="rounded-md border border-[var(--border)] bg-white px-4 py-2 text-sm font-medium" href={agent.demoUrl} target="_blank" rel="noopener noreferrer">在线体验</a>}{latest&&<DownloadButton versionId={latest.id}/>}</div></div><section className="mt-12 grid gap-10 lg:grid-cols-[1fr_320px]"><div><h2 className="text-2xl font-bold">产品介绍</h2><p className="mt-4 whitespace-pre-wrap leading-8 text-slate-700">{agent.description||agent.summary}</p><h2 className="mt-12 text-2xl font-bold">截图画廊</h2><div className="mt-4"><ScreenshotGallery screenshots={agent.screenshots||[]}/></div></div><aside><h2 className="text-lg font-semibold">历史版本</h2><div className="mt-4"><VersionList versions={versions.docs}/></div></aside></section></article>}
